// <auto-generated />
using System;
using Majstor_bob.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Majstor_bob.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608093204_UpdateConection")]
    partial class UpdateConection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Majstor_bob.Models.firme", b =>
                {
                    b.Property<int>("id_firme")
                        .HasColumnType("int");

                    b.Property<int>("broj_dostupnih_radnika")
                        .HasColumnType("int");

                    b.Property<int>("broj_recenzija")
                        .HasColumnType("int");

                    b.Property<int>("broj_ukupnih_radnika")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("kraj_radnog_vremena")
                        .HasColumnType("time(6)");

                    b.Property<string>("naziv_firme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("opis_usluga")
                        .HasColumnType("longtext");

                    b.Property<int?>("pib")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("pocetak_radnog_vremena")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("prosek_ocena")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_firme");

                    b.HasIndex("pib")
                        .IsUnique();

                    b.ToTable("firme");
                });

            modelBuilder.Entity("Majstor_bob.Models.gradovi", b =>
                {
                    b.Property<int>("id_grad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_grad"));

                    b.Property<string>("naziv_grada")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("postanski_broj")
                        .HasColumnType("int");

                    b.HasKey("id_grad");

                    b.HasIndex("naziv_grada")
                        .IsUnique();

                    b.ToTable("gradovi");
                });

            modelBuilder.Entity("Majstor_bob.Models.gradovi_rada", b =>
                {
                    b.Property<int>("id_grad_rada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_grad_rada"));

                    b.Property<int>("doplata")
                        .HasColumnType("int");

                    b.Property<int>("id_grada")
                        .HasColumnType("int");

                    b.Property<int>("id_izvodjaca")
                        .HasColumnType("int");

                    b.Property<bool>("zona_rada")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id_grad_rada");

                    b.HasIndex("id_grada");

                    b.HasIndex("id_izvodjaca");

                    b.ToTable("gradovi_rada");
                });

            modelBuilder.Entity("Majstor_bob.Models.kategorije", b =>
                {
                    b.Property<int>("id_kategorije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_kategorije"));

                    b.Property<int?>("id_roditelja")
                        .HasColumnType("int");

                    b.Property<string>("naziv_kategorije")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_kategorije");

                    b.HasIndex("id_roditelja");

                    b.HasIndex("naziv_kategorije")
                        .IsUnique();

                    b.ToTable("kategorije");
                });

            modelBuilder.Entity("Majstor_bob.Models.klijenti", b =>
                {
                    b.Property<int>("id_klijent")
                        .HasColumnType("int");

                    b.Property<int?>("gradGdeKlijentRadid_grad")
                        .HasColumnType("int");

                    b.Property<int?>("id_grad_rada")
                        .HasColumnType("int");

                    b.HasKey("id_klijent");

                    b.HasIndex("gradGdeKlijentRadid_grad");

                    b.HasIndex("id_grad_rada")
                        .IsUnique();

                    b.ToTable("klijenti");
                });

            modelBuilder.Entity("Majstor_bob.Models.korisnici", b =>
                {
                    b.Property<int>("id_korisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_korisnik"));

                    b.Property<bool>("aktivan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("blokiran")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("datum_registacije")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_flaged")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("poslednji_login")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("profilna_slika")
                        .HasColumnType("longtext");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefon")
                        .HasColumnType("longtext");

                    b.Property<int>("tip_korisnika")
                        .HasColumnType("int");

                    b.Property<DateTime>("token_istice")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("verifikovan")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id_korisnik");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("korisnici");
                });

            modelBuilder.Entity("Majstor_bob.Models.majstori", b =>
                {
                    b.Property<int>("id_majstora")
                        .HasColumnType("int");

                    b.Property<int>("broj_recenzija")
                        .HasColumnType("int");

                    b.Property<int?>("jmbg")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("kraj_radnog_vremena")
                        .HasColumnType("time(6)");

                    b.Property<string>("opis_usluga")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("pocetak_radnog_vremena")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("prosek_ocena")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_majstora");

                    b.HasIndex("jmbg")
                        .IsUnique();

                    b.ToTable("majstori");
                });

            modelBuilder.Entity("Majstor_bob.Models.obavestenja", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("korisnik_id")
                        .HasColumnType("int");

                    b.Property<string>("naslov")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("povezani_id")
                        .HasColumnType("int");

                    b.Property<bool>("procitano")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("tip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("korisnik_id");

                    b.HasIndex("povezani_id");

                    b.ToTable("obavestenja");
                });

            modelBuilder.Entity("Majstor_bob.Models.ocene", b =>
                {
                    b.Property<int>("id_ocene")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_ocene"));

                    b.Property<int>("id_izvodjaca")
                        .HasColumnType("int");

                    b.Property<int>("id_klijenta")
                        .HasColumnType("int");

                    b.Property<int>("ocena_brzine")
                        .HasColumnType("int");

                    b.Property<int>("ocena_cena")
                        .HasColumnType("int");

                    b.Property<int>("ocena_kvaliteta")
                        .HasColumnType("int");

                    b.Property<int>("ocena_odnosa")
                        .HasColumnType("int");

                    b.Property<string>("odgovor")
                        .HasColumnType("longtext");

                    b.Property<string>("opis_recenzije")
                        .HasColumnType("longtext");

                    b.HasKey("id_ocene");

                    b.HasIndex("id_izvodjaca");

                    b.HasIndex("id_klijenta");

                    b.ToTable("ocene");
                });

            modelBuilder.Entity("Majstor_bob.Models.poruke", b =>
                {
                    b.Property<int>("id_poruke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_poruke"));

                    b.Property<int>("id_razgovora")
                        .HasColumnType("int");

                    b.Property<int>("posiljac_id")
                        .HasColumnType("int");

                    b.Property<string>("tekst")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("vreme")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_poruke");

                    b.HasIndex("id_razgovora");

                    b.HasIndex("posiljac_id");

                    b.ToTable("porukes");
                });

            modelBuilder.Entity("Majstor_bob.Models.prijave", b =>
                {
                    b.Property<int>("id_prijave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_prijave"));

                    b.Property<string>("admin_komentar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_prijavljaca")
                        .HasColumnType("int");

                    b.Property<int>("id_prijavljena_osoba")
                        .HasColumnType("int");

                    b.Property<DateTime>("kreirano")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("obradjeno")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("razlog")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_prijave");

                    b.HasIndex("id_prijavljaca");

                    b.HasIndex("id_prijavljena_osoba");

                    b.ToTable("prijave");
                });

            modelBuilder.Entity("Majstor_bob.Models.pripada", b =>
                {
                    b.Property<int>("id_pripada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_pripada"));

                    b.Property<int>("id_izvodjaca")
                        .HasColumnType("int");

                    b.Property<int>("id_kategorije")
                        .HasColumnType("int");

                    b.HasKey("id_pripada");

                    b.HasIndex("id_izvodjaca");

                    b.HasIndex("id_kategorije");

                    b.ToTable("pripada");
                });

            modelBuilder.Entity("Majstor_bob.Models.razgovor", b =>
                {
                    b.Property<int>("id_razgovora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_razgovora"));

                    b.Property<int>("id_klijent")
                        .HasColumnType("int");

                    b.Property<int>("id_majstor")
                        .HasColumnType("int");

                    b.Property<int?>("korisniciid_korisnik")
                        .HasColumnType("int");

                    b.HasKey("id_razgovora");

                    b.HasIndex("id_klijent");

                    b.HasIndex("id_majstor");

                    b.HasIndex("korisniciid_korisnik");

                    b.ToTable("razgovor");
                });

            modelBuilder.Entity("Majstor_bob.Models.zahtevi", b =>
                {
                    b.Property<int>("id_zahteva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_zahteva"));

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("datum")
                        .HasColumnType("date");

                    b.Property<int>("id_izvodjaca")
                        .HasColumnType("int");

                    b.Property<int>("id_klijenta")
                        .HasColumnType("int");

                    b.Property<string>("opis_radova")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("vreme")
                        .HasColumnType("time(6)");

                    b.HasKey("id_zahteva");

                    b.HasIndex("id_izvodjaca");

                    b.HasIndex("id_klijenta");

                    b.ToTable("zahtevi");
                });

            modelBuilder.Entity("Majstor_bob.Models.zakazivanje", b =>
                {
                    b.Property<int>("id_zakazivanja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_zakazivanja"));

                    b.Property<int>("cena_donja")
                        .HasColumnType("int");

                    b.Property<int>("cena_gornja")
                        .HasColumnType("int");

                    b.Property<bool>("da_li_je_placeno")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("datum")
                        .HasColumnType("date");

                    b.Property<int>("id_zahteva")
                        .HasColumnType("int");

                    b.Property<int?>("klijentiid_klijent")
                        .HasColumnType("int");

                    b.Property<int>("konacna_cena")
                        .HasColumnType("int");

                    b.Property<int?>("korisniciid_korisnik")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("kraj")
                        .HasColumnType("time(6)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("otkazano_od")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("pocetak")
                        .HasColumnType("time(6)");

                    b.Property<string>("razlog_otkazivanja")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_zakazivanja");

                    b.HasIndex("id_zahteva");

                    b.HasIndex("klijentiid_klijent");

                    b.HasIndex("korisniciid_korisnik");

                    b.ToTable("zakazivanje");
                });

            modelBuilder.Entity("Majstor_bob.Models.zapisnik_admin", b =>
                {
                    b.Property<int>("id_zapisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_zapisnik"));

                    b.Property<string>("akcija")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_admina")
                        .HasColumnType("int");

                    b.Property<string>("ip_adresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_zapisnik");

                    b.HasIndex("id_admina");

                    b.ToTable("zapisnik_admin");
                });

            modelBuilder.Entity("Majstor_bob.Models.firme", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "korisnik")
                        .WithOne("firme")
                        .HasForeignKey("Majstor_bob.Models.firme", "id_firme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("Majstor_bob.Models.gradovi_rada", b =>
                {
                    b.HasOne("Majstor_bob.Models.gradovi", "grad")
                        .WithMany("gradovi_rad")
                        .HasForeignKey("id_grada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.korisnici", "Izvodjac")
                        .WithMany("gradovi_rad")
                        .HasForeignKey("id_izvodjaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvodjac");

                    b.Navigation("grad");
                });

            modelBuilder.Entity("Majstor_bob.Models.kategorije", b =>
                {
                    b.HasOne("Majstor_bob.Models.kategorije", "roditelj")
                        .WithMany("pod_kategorija")
                        .HasForeignKey("id_roditelja")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("roditelj");
                });

            modelBuilder.Entity("Majstor_bob.Models.klijenti", b =>
                {
                    b.HasOne("Majstor_bob.Models.gradovi", "gradGdeKlijentRad")
                        .WithMany()
                        .HasForeignKey("gradGdeKlijentRadid_grad");

                    b.HasOne("Majstor_bob.Models.gradovi", null)
                        .WithOne()
                        .HasForeignKey("Majstor_bob.Models.klijenti", "id_grad_rada");

                    b.HasOne("Majstor_bob.Models.korisnici", "korisnik")
                        .WithOne("klijenti")
                        .HasForeignKey("Majstor_bob.Models.klijenti", "id_klijent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gradGdeKlijentRad");

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("Majstor_bob.Models.majstori", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "korisnik")
                        .WithOne("majstori")
                        .HasForeignKey("Majstor_bob.Models.majstori", "id_majstora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("korisnik");
                });

            modelBuilder.Entity("Majstor_bob.Models.obavestenja", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "korsinik")
                        .WithMany("obavestenje_primalac")
                        .HasForeignKey("korisnik_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.korisnici", "povezan")
                        .WithMany("obavestenja_posiljac")
                        .HasForeignKey("povezani_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("korsinik");

                    b.Navigation("povezan");
                });

            modelBuilder.Entity("Majstor_bob.Models.ocene", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "izvodjac")
                        .WithMany("ocenjen_izvodjac")
                        .HasForeignKey("id_izvodjaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.klijenti", "klijent")
                        .WithMany("ocene")
                        .HasForeignKey("id_klijenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("izvodjac");

                    b.Navigation("klijent");
                });

            modelBuilder.Entity("Majstor_bob.Models.poruke", b =>
                {
                    b.HasOne("Majstor_bob.Models.razgovor", "razgovor")
                        .WithMany("poruke")
                        .HasForeignKey("id_razgovora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.korisnici", "posiljac")
                        .WithMany()
                        .HasForeignKey("posiljac_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("posiljac");

                    b.Navigation("razgovor");
                });

            modelBuilder.Entity("Majstor_bob.Models.prijave", b =>
                {
                    b.HasOne("Majstor_bob.Models.klijenti", "klijent")
                        .WithMany("ko_prijavljuje")
                        .HasForeignKey("id_prijavljaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.korisnici", "izvodjac")
                        .WithMany("prijavljena_osoba")
                        .HasForeignKey("id_prijavljena_osoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("izvodjac");

                    b.Navigation("klijent");
                });

            modelBuilder.Entity("Majstor_bob.Models.pripada", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "izvodjac")
                        .WithMany("kategorija_kojoj_pripada")
                        .HasForeignKey("id_izvodjaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.kategorije", "kategorija")
                        .WithMany("kategorije_izvodjaca")
                        .HasForeignKey("id_kategorije")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("izvodjac");

                    b.Navigation("kategorija");
                });

            modelBuilder.Entity("Majstor_bob.Models.razgovor", b =>
                {
                    b.HasOne("Majstor_bob.Models.klijenti", "klijent")
                        .WithMany("razgovors")
                        .HasForeignKey("id_klijent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.korisnici", "izvodjac")
                        .WithMany()
                        .HasForeignKey("id_majstor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.korisnici", null)
                        .WithMany("razgovor")
                        .HasForeignKey("korisniciid_korisnik");

                    b.Navigation("izvodjac");

                    b.Navigation("klijent");
                });

            modelBuilder.Entity("Majstor_bob.Models.zahtevi", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "izvodjac")
                        .WithMany("kome_salje_zahtev")
                        .HasForeignKey("id_izvodjaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.klijenti", "klijent")
                        .WithMany("sender_zahteva")
                        .HasForeignKey("id_klijenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("izvodjac");

                    b.Navigation("klijent");
                });

            modelBuilder.Entity("Majstor_bob.Models.zakazivanje", b =>
                {
                    b.HasOne("Majstor_bob.Models.zahtevi", "zahtev")
                        .WithMany("zakazivanja")
                        .HasForeignKey("id_zahteva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Majstor_bob.Models.klijenti", null)
                        .WithMany("kome_salje_zakaz")
                        .HasForeignKey("klijentiid_klijent");

                    b.HasOne("Majstor_bob.Models.korisnici", null)
                        .WithMany("izvodjac_koj_zakazuje")
                        .HasForeignKey("korisniciid_korisnik");

                    b.Navigation("zahtev");
                });

            modelBuilder.Entity("Majstor_bob.Models.zapisnik_admin", b =>
                {
                    b.HasOne("Majstor_bob.Models.korisnici", "admin")
                        .WithMany("zapisnik")
                        .HasForeignKey("id_admina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("Majstor_bob.Models.gradovi", b =>
                {
                    b.Navigation("gradovi_rad");
                });

            modelBuilder.Entity("Majstor_bob.Models.kategorije", b =>
                {
                    b.Navigation("kategorije_izvodjaca");

                    b.Navigation("pod_kategorija");
                });

            modelBuilder.Entity("Majstor_bob.Models.klijenti", b =>
                {
                    b.Navigation("ko_prijavljuje");

                    b.Navigation("kome_salje_zakaz");

                    b.Navigation("ocene");

                    b.Navigation("razgovors");

                    b.Navigation("sender_zahteva");
                });

            modelBuilder.Entity("Majstor_bob.Models.korisnici", b =>
                {
                    b.Navigation("firme")
                        .IsRequired();

                    b.Navigation("gradovi_rad");

                    b.Navigation("izvodjac_koj_zakazuje");

                    b.Navigation("kategorija_kojoj_pripada");

                    b.Navigation("klijenti")
                        .IsRequired();

                    b.Navigation("kome_salje_zahtev");

                    b.Navigation("majstori")
                        .IsRequired();

                    b.Navigation("obavestenja_posiljac");

                    b.Navigation("obavestenje_primalac");

                    b.Navigation("ocenjen_izvodjac");

                    b.Navigation("prijavljena_osoba");

                    b.Navigation("razgovor");

                    b.Navigation("zapisnik");
                });

            modelBuilder.Entity("Majstor_bob.Models.razgovor", b =>
                {
                    b.Navigation("poruke");
                });

            modelBuilder.Entity("Majstor_bob.Models.zahtevi", b =>
                {
                    b.Navigation("zakazivanja");
                });
#pragma warning restore 612, 618
        }
    }
}
